sudo: required

services:
  - docker

before_install:
  - mkdir -p output
  - docker pull ameausoone/docker-image-asciidoctor-reveal.js

script:
  - docker run -v $TRAVIS_BUILD_DIR/slides/:/opt/slides/ -v $TRAVIS_BUILD_DIR/output:/opt/output/ --name asciidoc-to-revealjs-prez ameausoone/docker-image-asciidoctor-reveal.js make

after_error:
  - docker logs asciidoc-to-revealjs-prez

after_failure:
  - docker logs asciidoc-to-revealjs-prez

after_success:
  - cd output ; mv README.html index.html ; cp -R ../images images
  - git init
  - git config user.name "${GH_USER_NAME}"
  - git config user.email "{GH_USER_EMAIL}"
  - git add . ; git commit -m "Deploy to GitHub Pages"
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:gh-pages > /dev/null 2>&1
