version: '2'
services:
  prez:
    image: ameausoone/docker-image-asciidoctor-reveal.js
    ports:
    - "8000:8000"
    volumes:
    - ./slides/:/opt/slides/
    - ./output/:/opt/output/
    environment:
      INDEX: history.html
